name: Packages

on:
  repository_dispatch:
    branches:
      - main

  push:
    paths:
      - packages/grid/**

    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  packages: write
  deployments: write
  statuses: write

jobs:
  packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx nx affected --target=release --parallel=3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
